# Generated by Django 3.0.5 on 2020-08-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycles',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
