# Generated by Django 3.0.5 on 2020-09-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='updateAt',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='statements',
            old_name='updateAt',
            new_name='updatedAt',
        ),
    ]
