# Generated by Django 3.0.5 on 2020-09-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200904_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='is_read',
            field=models.CharField(default='', max_length=10),
        ),
    ]
