# Generated by Django 3.0.5 on 2020-08-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200828_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycles',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
