# Generated by Django 3.0.5 on 2020-08-28 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200828_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_statements', to='api.Cycles'),
        ),
        migrations.AlterField(
            model_name='statements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statements', to=settings.AUTH_USER_MODEL),
        ),
    ]
